### ISSUE TITLE
Not bounded by y=0

### ISSUE THREAD

**Issue by saxocellphone** [saxocellphone/Three#6]
For now, I think the solid of revolution should be bounded by x = 0 and y = 0, and a user set vertical bound. (Didn't get there yet) the x=0 part is working fine, but the solid is not bounded by y=0. For example, if you graph sin(x), you can see it's not bounded by y=0. If I make an if statement to check if the y-coordinate is less than 0, and stop graphing it if y < 0, you can see some serious bug caused by intervals.

**Comment by winstliu** [comment]
I believe this is fixed with the introduction of custom (vertical) bounds and a custom axis of rotation.
