### ISSUE TITLE
Unknown function ln

### ISSUE THREAD

**Issue by PioneerAPCS-20** [saxocellphone/Three#71]
The calculator doesn't recognize when I use the absolute value bars. The reason I'm trying to use them is because the calculator does not handle negatives.

I'm assuming this hasn't been added to the calculator yet and I know it's a work in progress.

**Comment by winstliu** [comment]
Hey, an opportunity to revisit this project. I'll take a look if I have the time :)

**Comment by winstliu** [comment]
This is fixed for simple scenarios like `y=|-x|`. If you're doing something more complicated, you'll want to use abs(), e.g. `y=abs(-3 + abs(-x))`.
