### ISSUE TITLE
Rotates around x-axis instead of y-axis

### ISSUE THREAD

**Issue by randy-shi** [saxocellphone/Three#74]
My input was function 1: y=1/x     Bound 1: x=1/2       Bound 2: x=4            around y=0
And it gave me a image of everything except it was sideways.
![image](https://user-images.githubusercontent.com/94768918/149822443-7e78a0d0-8b08-4356-8474-531fa1e33d67.png)

**Comment by winstliu** [comment]
I think this is working as intended - you are rotating around the _line_ `y = 0` (which appears as a _horizontal_ line). Right?
