### ISSUE TITLE
Solid is incorrect when bound1 is negative

### ISSUE THREAD

**Issue by winstliu** [saxocellphone/Three#9]
A couple of fun ones to look at:
<s>-x, -4, 0, 4</s>
<s>x, -4, 0, 4</s>
x, -4, 0, 0
<s>x, -4, 0, -4</s>

**Comment by saxocellphone** [comment]
I think I fixed it with the latest update. But you should take a look for sure

**Comment by winstliu** [comment]
x, -4, 0, 0 is still invisible if you rotate it.

**Comment by winstliu** [comment]
Closed by c44ab49929aada9ed71206c8bdf07707264a2419.
